apiVersion: v1
kind: Service
metadata:
  name: phi2-webui
  namespace: phi2
spec:
  selector:
    app: phi2-webui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000  # Пробрасываем порт контейнера