apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: patch-ollama.yaml
    target:
      kind: Deployment
      name: ollama-phi2
  - path: patch-webui.yaml
    target:
      kind: Deployment
      name: phi2-webui