apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama-phi2
  namespace: phi2
spec:
  template:
    spec:
      containers:
      - name: ollama
        env:
        - name: OLLAMA_KEEP_ALIVE
          value: "30m"
        - name: OLLAMA_NO_MMAP
          value: "true"
        resources:
          limits:
            cpu: "2"
            memory: "4Gi"
          requests:
            cpu: "1"
            memory: "2Gi"