apiVersion: apps/v1
kind: Deployment
metadata:
  name: phi2-webui
  namespace: phi2
spec:
  template:
    spec:
      containers:
      - name: webui
        resources:
          limits:
            cpu: "1"
            memory: "2Gi"
          requests:
            cpu: "0.5"
            memory: "1Gi"