apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: phi2
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Cellofworld/phi2.git
    path: overlays/production
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: phi2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true